### ISSUE TITLE
Real Time Clock is not updating using libnds time() implementation

### ISSUE THREAD

**Issue by IvanVeloz** [melonDS-emu/melonDS#2038] opened 2024-05-11 22:55 UTC
When using the time() implementation of libnds, if `time()` is called, the time value returned stays the same. 

For an example, you can use the RealTimeClock example, part of DevKitPro. The clock will stay stuck at whatever time you opened the ROM (see [.nds and code](https://github.com/melonDS-emu/melonDS/files/15284488/RealTimeClock.zip)). I am actually not sure if it's stuck at the time the emulation starts, at the time the ROM loads, or at the first 
time `time()` is called.

See a [video of the behavior](https://github.com/melonDS-emu/melonDS/assets/146200551/e5480d22-51c2-43de-a40c-66a043e7f37d).

I tested the same binary attached on real hardware (Nintendo DS Lite) and the clock updates. The BIOS used on melonDS was dumped from the same unit.

If you don't have the time to read through libnds code, let me know. I can give it a try. I am going to do a homebrew app making extensive use of the RTC, so I am willing to volunteer time for this issue. Just let me know.

Thank you for the great emulator, the WiFi will save me so much development time!

Best regards,
Ivan

**Comment by Jaklyy** [comment] 2024-05-11 23:04
this is fixed in dev builds
although it's worth noting that this is a result of weird implementation by devkitpro. since iirc this rom also wouldn't work on 3ds, due to the way the 3ds handles (or rather, doesn't handle) certain rtc regs
i forget the exact reasoning why (i think it's something to do with alarm regs?)

**Comment by IvanVeloz** [comment] 2024-05-11 23:39
Thank you for the fix. I built the main branch and yes, works perfectly.

I might raise the issue with DevKitPro after I get more familiar with their library.

**Closed** 2024-05-11 23:39 UTC

**Comment by IvanVeloz** [comment] 2024-05-12 01:01
OK, I thought I was going crazy for a moment.

The latest build as of today works, but only for a few seconds or minutes. After that, it stops working. I tried a lot of things: deleting the build, deleting my copy of the repo, restarting opening different NDS files. I don't know what makes it work again, but it's rare that it starts working again. I think works again when I delete the entire repo, but that makes absolutely no sense to me.

The crazier thing is I thought this was macOS somehow caching the melonDS executable... but... I switched to my Linux PC and got the same result (it did last a little longer though). The Mac is a Mac mini M1. The PC is a Ryzen 3600 running an Ubuntu toolbox container on Fedora.

Are you able to replicate this? I'm at commit `c85a2103bbd41e7119e7d41daa5180dee823b591`.

**Comment by IvanVeloz** [comment] 2024-05-12 01:11
Okay, I found something interesting. If you disable "Boot game directly" on the Emu settings, the homebrew starts working for a while then stops. The difference is that it always starts working.

**Comment by Jaklyy** [comment] 2024-05-12 01:14
i can also reproduce this on windows
that's very odd
needs deleting rtc.bin to fix temporarily and then it breaks again

**Comment by Arisotura** [comment] 2024-05-13 12:10
huh, that's interesting to know

I'll look into it someday (when I'm not in the midst of a big refactor)
