### ISSUE TITLE
Can't transfer Manaphy's egg

### ISSUE THREAD

**Issue by nonsio280** [melonDS-emu/melonDS#1541] opened 2022-10-19 17:17 UTC
I tried to transfer the Manaphy's egg from the italian version of Pokemon Guardian Signs to Pokemon Diamond, without success. This feature requires a working local multiplayer connection, and I used the most recent version of MelonDS (not the stable release, this one b6776bd826fbe31c62a7222d34cf387fb6f3d260 )

I attach the save files

[Saves.zip](https://github.com/melonDS-emu/melonDS/files/9822784/Saves.zip)

**Comment by KostaSaizo7** [comment] 2022-10-19 19:54
I have reproduced this. The games can acknowledge each other but when the transfer is about to happen, it just won't connect.
![manaphy1](https://user-images.githubusercontent.com/39852873/196790712-fe0ad079-2c01-41bc-8318-3bf08d56bd0f.png)
![manaphy2](https://user-images.githubusercontent.com/39852873/196790718-2f850fa2-2748-4607-94b6-b9d9e68d6797.png)

**Comment by nonsio280** [comment] 2022-10-19 22:13
> I have reproduced this. The games can acknowledge each other but when the transfer is about to happen, it just won't connect. ![manaphy1](https://user-images.githubusercontent.com/39852873/196790712-fe0ad079-2c01-41bc-8318-3bf08d56bd0f.png) ![manaphy2](https://user-images.githubusercontent.com/39852873/196790718-2f850fa2-2748-4607-94b6-b9d9e68d6797.png)

Exaclty. It never actually worked properly, but a long time ago (maybe version 8.4?) I managed to pull this off by disabling framerate limiter and a long process of trial and errors. I don't know why, but maybe this information can help developers

**Comment by patataofcourse** [comment] 2022-10-19 22:32
Yeah, that's just how the local wifi implementation used to work, disable framerate limiter and pray to your deity of choice. It's since been completely revamped, though, so this error is more likely than not something unrelated.

**Comment by nonsio280** [comment] 2022-10-19 23:35
> Yeah, that's just how the local wifi implementation used to work, disable framerate limiter and pray to your deity of choice. It's since been completely revamped, though, so this error is more likely than not something unrelated.

I mean JIT was definetly implemented at the time. I'm no programmer, I wish I could help more.

**Comment by KostaSaizo7** [comment] 2022-10-20 05:41
Steps to reproduce:
Boot Pokemon Ranger Guardian Signs with op's save file (prefferably use the US version because the EU boots the game in italian language). 
Ranger Net> Send a a pokemon> Send a Manaphy Egg> Transmit

Then boot Pokemon Diamond with op's save file. In the main menu the message in the first image will appear. Select "Connect
to Pokemon Ranger" and that's it. The games don't connect and the diamond instance freezes.

**Comment by patataofcourse** [comment] 2022-10-20 08:05
Would be nice to test this with Platinum or the other Ranger games, but not sure if anyone will have a save lying around

**Comment by nonsio280** [comment] 2022-10-20 12:33
I just tested this with Platinum and Soul Silver, with the same results. Unfortunately I don't have other Ranger games to test

**Comment by KostaSaizo7** [comment] 2022-10-20 15:07
I tried with Pokemon Ranger Shadows of Almia and Heartgold, it doesn't work
![image](https://user-images.githubusercontent.com/39852873/196986707-dbe99bfc-706f-409d-960b-5c121ff55071.png)

**Comment by nonsio280** [comment] 2022-10-20 18:50
> I tried with Pokemon Ranger Shadows of Almia ~and Heartgold, it doesn't work~ Edit: Nevermind, I'm not good at reading. It says that the transfer must be done to Pearl or Diamond. So I tried Pearl and it works
> 
> ![image](https://user-images.githubusercontent.com/39852873/196988595-c5abbd6e-8ed2-4342-bf87-09734abc24f5.png)

That's weird, I remember it was possible on hardware, even if Heart Gold isn't explicitly mentioned. I think this should be tested with 2 real consoles, just to be sure.

**Comment by KostaSaizo7** [comment] 2024-06-16 05:48
This is now fixed! Possibly by https://github.com/melonDS-emu/melonDS/pull/2067

![ranger manaphy egg](https://github.com/melonDS-emu/melonDS/assets/39852873/778d4ebd-1ffa-47c4-8961-37af3ae885a6)
![ranger manaphy egg 2](https://github.com/melonDS-emu/melonDS/assets/39852873/f00af618-408e-440e-b037-83c53637c564)

**Closed** 2024-06-16 09:00 UTC
