### ISSUE TITLE
Turning in place on the stairs in the Luigi's Mansion stage of Mario Kart DS (USA) should crash the game but doesn't

### ISSUE THREAD

**Issue by ghost** [melonDS-emu/melonDS#908] opened 2020-12-27 10:42 UTC
On real hardware stopping in place and pressing A + B to drift in place crashes the game. In MelonDS it doesn't for some reason. Here's a more detailed explanation and demonstration of the crash.

https://youtu.be/8kpaIrfYqw4?t=234

**Comment by RSDuck** [comment] 2020-12-27 20:02
this is probably because we don't have a proper PU emulation

**Comment by poudink** [comment] 2020-12-28 02:17
duplicate of https://github.com/Arisotura/melonDS/issues/96

**Comment by Tiberius1437** [comment] 2020-12-28 05:14
My report is more coherent and provides actual evidence. Close the other one.

**Comment by WaluigiWare64** [comment] 2020-12-28 21:26
Well the other issue was first, and this one is a duplicate.
This issue is the one that should be closed, as this one already has been reported.

**Comment by Tiberius1437** [comment] 2020-12-28 21:50
Or just fix it and close both of them.

**Closed** 2022-09-04 15:36 UTC
Labels: duplicate
