### ISSUE TITLE
Failed to load rom from command line when file name has special character

### ISSUE THREAD

**Issue by Homaxz** [melonDS-emu/melonDS#1689] opened 2023-05-26 08:01 UTC
I'm trying to run Pokemon SoulSilver from the command line as such:

`melonds.exe "C:\Users\ADMIN\Desktop\Pokémon - SoulSilver Version.nds"`

melonDS starts and gives the error "Failed to load the ROM."

Starting the rom from the GUI>file option works fine. 
Renaming the rom and to "Pokemon - SoulSilver Version.nds" makes it load through the cmd as well.

**Comment by RSDuck** [comment] 2023-05-26 09:48
which version are you using, I think we fixed this one already.

**Comment by Homaxz** [comment] 2023-05-26 12:59
Sorry I forgot to mention. 0.9.5

**Comment by RSDuck** [comment] 2023-05-26 13:01
then it is a duplicate of #1556

**Closed by RSDuck** 2023-05-26 13:01 UTC
