### ISSUE TITLE
Multi language games doesn't use the one set in the firmware settings

### ISSUE THREAD

**Issue by Miguel-hrvs** [melonDS-emu/melonDS#2057] opened 2024-06-07 16:38 UTC
The problem doesn't happen in the stable 0.9.5 from 2022, but it happens in the master branch.
![melonds-language-problem](https://github.com/melonDS-emu/melonDS/assets/81558772/7449a074-3b3c-4ced-b965-549a319cbed5)

**Comment by Miguel-hrvs** [comment] 2024-06-07 20:23
Thanks a lot, your fix works perfectly :)

**Comment by CasualPokePlayer** [comment] 2024-06-07 20:32
The PR hasn't been merged yet.

**Comment by Miguel-hrvs** [comment] 2024-06-07 20:42
I downloaded it from actions

**Comment by Miguel-hrvs** [comment] 2024-06-07 20:42
Should I reopen it until it's merged?

**Comment by CasualPokePlayer** [comment] 2024-06-07 20:43
Yes. When it's merged the issue (i.e. actually in official builds) the issue is automatically closed.

**Closed** 2024-07-11 13:55 UTC
