### ISSUE TITLE
[Feature Request] Add a option to let the user manually change the fps to 100, 110, 120 etc.

### ISSUE THREAD

**Issue by Chummpp** [melonDS-emu/melonDS#1553] opened 2022-11-05 18:49 UTC
So far the user is only able to run games at 144 fps or 370fps. The emulator needs to have a option where the user can choose to keep the fps at 100, 110, 120 etc. Not only that but the emulator running at 144 fps or higher makes the cpu and the gpu hotter than they should be, which makes the lifespan of the cpu and gpu shorter. Please give us the choice to manually change the fps to any number we want by implementing some sort of option.

**Comment by nadiaholmquist** [comment] 2022-11-05 18:56
How are you getting 144? Is that with the vsync option in the video settings and framerate limiter disabled?

Normally the emulator should be running at 60FPS.

**Comment by Chummpp** [comment] 2022-11-05 19:04
> How are you getting 144? Is that with the vsync option in the video settings and framerate limiter disabled?
> 
> Normally the emulator should be running at 60FPS.

Yes when vsync is enabled the fps is limited by the monitor or tv refresh rate. 

I just thought about something. I wander if changing the monitor refresh rate to 120 hz from the gpu settings will make the emulator run at 120 fps.

**Comment by nadiaholmquist** [comment] 2022-11-05 19:06
It would. You should also be able to change the vsync interval setting to run at half, quarter, etc. your monitor's refresh rate.

**Comment by Chummpp** [comment] 2022-11-05 19:10
> It would. You should also be able to change the vsync interval setting to run at half, quarter, etc. your monitor's refresh rate.

I still think the emulator should have the option to let the user manually choose any fps without changing the monitor frequincy.

**Comment by patataofcourse** [comment] 2022-11-05 20:11
duplicate of #947

**Comment by acxz** [comment] 2024-04-25 00:20
@nadiaholmquist can this be closed due to https://github.com/melonDS-emu/melonDS/commit/7dd4152d6711db76fbe2a2acffcc208a524bb25d?

**Closed** 2024-04-25 00:26 UTC
